In [1]:
import numpy as np

Suppose that we have the following matrix of transition probabilities (see [Markov Chains](https://www.youtube.com/watch?v=i3AkTO9HLXo&t=4s))

$$ P(x,y) =
\begin{bmatrix} 
0.2 & 0.6 & 0.2 \\
0.3 & 0 & 0.7 \\
0.5 & 0 & 0.5
\end{bmatrix},
$$

where the states are $\, \alpha, \beta, \gamma \,$ ($\alpha$ in 1st row, 1st col, $\beta$ in 2nd row, 2nd col, $\gamma$ in 3rd row, 3rd col).

The probabilities of each state is denoted by a **row** vector $\, \pi. \,$ 

Suppose that our initial state is $\, X_0 = \beta. \,$ Then the initial (probability) distribution is $\, \pi^{(0)} = [0 \quad 1 \quad 0]. \,$ This is because if $\, X_0 = \beta, \,$ we know for sure that the system starts in state $\beta$. So there is no uncertainty; it is a deterministic condition. If we were told that the initial state is random such that the probability of starting at each state is for example 0.3, 0.3, 0.4 for $\, \alpha, \beta, \gamma, \,$ respectively, then the initial distribution would be $\, \pi^{(0)} = [0.3 \quad 0.3 \quad 0.4]. \,$ 

The distribution of the next state $\, X_1 \,$ can be calculated with vector matrix multiplication

$$ \pi^{(1)} = \pi^{(0)} P. $$

Similarly, the distribution of $\, X_2 \,$ can be calculated as

$$ \pi^{(2)} = \pi^{(1)} P $$

and so on.

(note that the notation $\, \pi^{(i)} \,$ is used to denote the probability distribution of the *ith* state. This notation style is taken from [here](https://www.probabilitycourse.com/chapter11/11_2_3_probability_distributions.php))

In [4]:
P = np.array([0.2, 0.6, 0.2, 0.3, 0, 0.7, 0.5, 0, 0.5]).reshape(3,3)
pi_0 = np.array([0, 1, 0])[np.newaxis, :]

In [6]:
pi_1 = pi_0 @ P

In [7]:
pi_1

array([[0.3, 0. , 0.7]])

- Note that this first operation just picks the row corresponding to $\, \beta \,$ from the transition matrix $\, P(x,y). \,$

In [8]:
pi_2 = pi_1 @ P

In [9]:
pi_2

array([[0.41, 0.18, 0.41]])

Continuing to move up in the states will bring us to the stationary distribution (i.e., the probabilities of each state will converge to some constant) if the following conditions are satisfied

**1**. Irreducibility: You can get from any state to any other state (possibly in multiple steps).
    
**2**. Aperiodicity: The chain doesn't get "stuck" in cycles; each state returns to itself at some irregular intervals.
    
**3**. Finite state space $\, \mathbb{S}: \,$ The *state space* of a Markov chain is the set of all possible states the system can be in (in our example, the possible states are $\, \alpha, \beta, \gamma \, \rightarrow \, \mathbb{S} = \{\alpha, \beta, \gamma \}).$

If all these conditions hold, then regardless where we start $\, (\text{i.e., regardless of } X_0), \,$ the (probability) distribution of $\, X_n \,$ will converge

$$ \underset{n \rightarrow \infty}{\text{lim }} \pi_n = \pi $$

where $\, \pi \,$ is the **stationary distribution** of the Markov chain, and it satisfies

$$ \pi P = \pi $$

and

$$ \sum_{\pi_i} \pi_i = 1. $$

In [11]:
def stationary_distr(n, pi, P):
    """
    Args:
        n: the number of steps to take (i.e., the number of states to move forward)
        pi: the initial (probability) distribution of each state
        P: the transition matrix
    """
    for i in range(n):
        pi = pi @ P
    return pi

In [18]:
stat_distr = stationary_distr(n=1000000, pi=pi_0, P=P)

In [19]:
stat_distr

array([[0.35211268, 0.21126761, 0.43661972]])

In [20]:
stat_distr.sum()

np.float64(0.9999999999999997)

**NOTE**

A Markov chain is defined by

**1. A state space**
- A set of possible states $\, \mathbb{S} \,$ (e.g., $\alpha, \beta, \gamma).$
    
**2. A transition matrix P**
- This gives the probabilities of moving between states; $\, P = [p_{ij}], \,$ where $\, p_{ij} = P(X_{n+1} = j | X_{n} = i).$

**3. An initial (probability) distribution $\pi^{(0)}$**
- The probability of starting in each state.